// Package localcipher encrypts with a key that lives only in the running
// process. It stands in for Cloud KMS with --no-auth, where the repository is
// in memory and its data disappears with the process as well.
package localcipher

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"

	"github.com/m-mizutani/goerr/v2"

	"github.com/m-mizutani/robin/pkg/domain/interfaces"
	"github.com/m-mizutani/robin/pkg/domain/model"
)

// keyName is recorded as EncryptedData.KeyName so a ciphertext of this cipher
// is never mistaken for a Cloud KMS one.
const keyName = "local-ephemeral"

// Cipher is AES-256-GCM under a key generated by New. Data it encrypts cannot
// be decrypted by another process or after this one exits.
type Cipher struct {
	aead cipher.AEAD
}

var _ interfaces.Cipher = &Cipher{}

func New() (*Cipher, error) {
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return nil, goerr.Wrap(err, "failed to generate local encryption key")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create AES cipher")
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create GCM")
	}
	return &Cipher{aead: aead}, nil
}

// Encrypt returns the nonce followed by the sealed plaintext.
func (c *Cipher) Encrypt(_ context.Context, plaintext, aad []byte) (*model.EncryptedData, error) {
	nonce := make([]byte, c.aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, goerr.Wrap(err, "failed to generate nonce")
	}
	return &model.EncryptedData{
		KeyName:    keyName,
		Ciphertext: c.aead.Seal(nonce, nonce, plaintext, aad),
	}, nil
}

func (c *Cipher) Decrypt(_ context.Context, data *model.EncryptedData, aad []byte) ([]byte, error) {
	if data.KeyName != keyName {
		return nil, goerr.New("ciphertext was not made by the local cipher", goerr.V("key_name", data.KeyName))
	}
	size := c.aead.NonceSize()
	if len(data.Ciphertext) < size {
		return nil, goerr.New("ciphertext is too short")
	}
	plaintext, err := c.aead.Open(nil, data.Ciphertext[:size], data.Ciphertext[size:], aad)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to decrypt with the local cipher")
	}
	return plaintext, nil
}
